### ISSUE TITLE
[rt9001] Collaboration w/ the fork "flower-platform/react-timeline-9001"

### ISSUE THREAD

**Issue by cristian-spiescu** [React9k/react-timeline-9000#183]
Hi there!

Congrats about this project! You've got here a really nice and promising piece of software!

My colleagues and I developed some while ago a [Gantt component for the Flex platform](http://gantt4flex.com/). We had tried a rewrite in JS (using GWT). And now we are in the React world, needing a good Gantt component. From the research I've made, I consider that this project is the best alternative for Gantt in React.

I like the approach of having externalized some features to the user. E.g. :
* zoom via CTRL + mouse wheel, 
* vertical scroll bar
* click on timeline header to zoom
* maybe synchronize w/ a table component, next to the gantt on the left side
* etc

By integrating this component into our app, we'll however need to add this kind of features. We'll probably create a wrapper around `Timeline` and add some features. In our case, they'd also depend on Redux.

**Question 1** But I was thinking that maybe it would be interesting if we contributed this back into the original project, i.e. here. What do you think about this?

**Question 2** If this is the case, I'd propose to have our component as a wrapper around the original one. So that `Timeline` can continue what it does best, and the other one, e.g. `TimelineExt`, that would have accessory features. This way, we'd have a minimal intrusion in `Timeline`, and it won't impact existing projects. 

Cheers!
Cristian

**Comment by vasdee** [comment]
Hi Cristian, 

Funnily enough, at one point in the project that we developed this library for, we were thinking of extending it to have optional gantt chart features. So, in principle I think this would be a great addition :)

Some initial thoughts, the state reducer pattern used to externalise some of the features was used so that the timeline could be just an efficient render of items on a grid and the add-ons could be implemented in 'user space' to add to the user experience as required. What  I would love to see in this project is a recipes or contrib area where people can add their custom additions to the timeline, and a developer coming across this project for the first time could pick and mix what they like for their solution, eg the gannt item rendering library or synchronised table etc. I'm happy for new hooks or props to be proposed in the base library to make this happen for your gantt needs, we can always bump the version up to indicate breaking changes if need be. 

This would come with some caveats though, any additions (especially around the item rendering) would probably have tie ins with a UI library, so i'm not sure how we'd manage that dependency. Maybe a new repo as you suggest, and a link in this readme to show where to find these additions... not sure on this, maybe @lilfolr can weigh in. 

Lastly, at one stage we were proposing to remove the interactjs dependency as it's not very 'reacty' and there is probably some much nicer ways to do this now. I would still like to do this, just don't have any reason to at the moment. It would still be worth keeping it in mind with your design, ideally we should be able to swap out interactjs with something else and the timeline should 'just keep working'

**Comment by cristian-spiescu** [comment]
Hi Rob,

And thanks for your reply.

> pick and mix what they like for their solution, eg the gannt item rendering library or synchronised table
Interesting. Didn't think of that. I'm an OOP developer at heart, and for me, by default customize = extend the class and override the functions. In this case a mechanism of "plugins" would be indeed interesting. And we'll see case per case if "extension points" are needed in the main code where the plugins will hook.

Once we have ideas, we'll share them here before developing stuff.

**Comment by cristian-spiescu** [comment]
Hi guys,

I hope you are doing well. Some news from our side.

I changed the name of this issue in `Collaboration w/ the fork "flower-platform/react-timeline-9000"`. I propose to keep here an open discussion regarding the process and integration flows between you and our repo, and any "admin" stuff.

Can you take a look at the first paragraph here: https://github.com/flower-platform/react-timeline-9000#flower-platform-fork-process. This describes how we intend to proceed when we contribute new work to this project. NB: our fork has a different default branch = `master-flower-platform`. Do you have any suggestions?

With our next contribution, I'll propose an update to `readme.md`; the creation of a "change log" section; we'll add links to issues there. We intend to update the issues so that they can also be used as individual "release notes" and/or doc where necessary.

We have integrated the Gantt into a project of ours. Currently all the new features reside in a superclass that extends `Timeline`. We'll work starting w/ mid March to move the code in our fork, and then to submit one PR per feature. We'll also move in our `readme.md` the list of TODOs that we have and notify you when we update them.

Best wishes,
Cristian

**Comment by cristian-spiescu** [comment]
Hi guys,

We are preparing to work on a lot of contributions. Can you please advice on your availability to integrate our work in the future? Rather low, medium, high?

I'm under the impression that maybe you are currently overloaded with other projects, and maybe you don't have a lot of time.

A hint from your side would help us organize our architecture. Either our project is a "secondary" fork (the current setting, cf. the "readme.md" of our fork). Or, if this main project is on hold, we'd adjust so that our fork is a ... fork; I mean going separate ways.

Thanks!

**Comment by lilfolr** [comment]
Hi Cristian,
I would appreciate if you kept the prs coming in. I will endeavor to review them within 2 days - hopefully quicker. Feel free to ping me if I miss a review 🙂

**Comment by cristian-spiescu** [comment]
Hi guys,

We have implemented a bunch of new features. And we'll implement other features these days.

The work we already done is currently [here](https://github.com/flower-platform/react-timeline-9000/pull/1). A quick summary (not yet curated/readable by everyone) is this one:

```
vertical lines on time unit

now indicator

Vertical grid:
* highlight weekends
* highlight custom intervals
* properties for vertical lines

default renderer: background gradient, border, glow on hover; fill
empty space with empty rows

timebar style changes
```

We want to:
* create one `.md` page; e.g. `docs/now-indicator.md` per feature, with some release notes/screen shots
* submit a/some merge requests from our fork to this repo

Can we squash the work we did (containing several features) in one commit and make a merge request? Or do you prefer to make one pull request per feature? => 4 or 5 pull requests? If OK for you, we'd prefer the first option. Starting from now, we'll have one feature => one branch.

**Comment by cristian-spiescu** [comment]
I forgot to add a screenshot:

![image](https://user-images.githubusercontent.com/4469897/134389803-ea1f152a-50e2-43d8-907c-d7ca4de352da.png)

**Comment by lilfolr** [comment]
Hey,
I think a PR per feature would be easier to review - that way we can address any questions/concerns without blocking the other features.

That being said if it's a pain to split up your change in to individual PRs I'll happily look over it all in one

**Comment by cristian-spiescu** [comment]
We've changed the name of our forked repo from "react-timeline-9000" to "react-timeline-9001". So that we can refer to our repo and version quicker as "rt9001". We'll prefix our issues here w/  `[rt9001] ...`.

**Comment by lilfolr** [comment]
Closing as we have other PRs/issues on specific features/bugs

**Comment by cristian-spiescu** [comment]
May I suggest to reopen and leave this issue open? I also updated its name. Let's use it for more or less "administrative" or architecture discussions between you guys and we = the Flower Platform team. What do you think about this? 

PS: I renamed our fork: _react-timeline-10000_, so that we can clearly distinguish the 2 repos. So that we can avoid misunderstandings when we joggle w/ the PRs among repos and branches.

FYI: we described our contribution process [here](https://github.com/flower-platform/react-timeline-10000).

**Comment by lilfolr** [comment]
I would prefer issues to close when complete (otherwise our backlog gets messy).  
Maybe we can use this: https://github.com/React9k/react-timeline-9000/discussions/255 for discussions
